Menu:
    Users:
        class: "IogUserBundle:User"
        route: "user"
        icon:  "user"
    Pages:
        class: "IogAdminBundle:Page"
        route: "page"
        icon:  "folder-open"
    Menus:
        class: "IogAdminBundle:Menu"
        route: "menu"
        icon:  "sitemap"
    Settings:
        class: "IogAdminBundle:Setting"
        route: "setting"
        icon:  "gear"
    Galleries:
        class: "IogAdminBundle:Gallery"
        route: "gallery"
        icon:  "picture"
Project Name: CMS