iog_web:
    resource: "@IogWebBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine
    
EndroidQrCodeBundle:
    resource:   "@EndroidQrCodeBundle/Controller/"
    type:       annotation
    prefix:     /qrcode
    
iog_admin:
    resource: "@IogAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
_security_login:
    pattern: /loginfb

fb_security_check:
    pattern: /loginfb_check
    defaults: { _controller: IogWebBundle:Default:fbUser }
    
_security_logout:
    pattern:  /logout
    
fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"   
    
iog_user:
    resource: "@IogUserBundle/Resources/config/routing.yml"
    prefix:   /
iog_web_default:
    pattern:  /{path}
    defaults: { _controller: IogWebBundle:Default:index, path: null }
    requirements:
      path: ".*"

