duedinoi_web:
    resource: "@DuedinoiWebBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine

duedinoi_admin:
    resource: "@DuedinoiAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

duedinoi_user:
    resource: "@DuedinoiUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

duedinoi_web_default:
    pattern:  /{_locale}/{path}
    defaults: { _controller: DuedinoiWebBundle:Default:index, path: null, locale: 'it' }
    requirements:
      path: ".*"

