security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       
                target: /
            anonymous:    true
    access_control:
        - { path: ^/.*/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/admin, role: ROLE_ADMIN }
        - { path: ^/.*/admin/, role: ROLE_ADMIN }
        - { path: ^/.*/admin/.*, role: ROLE_ADMIN }
        - { path: ^/.*/edit-profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/settings, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/my-profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/dashboard, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/photos, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/.*/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }