security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_BOT:         ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
            anonymous:    true
        default:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /it/dashboard
                always_use_default_target_path: false
                success_handler: user_security.component.authentication.handler.login_success_handler
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:    true
            switch_user: { role: ROLE_ADMIN, parameter: _want_to_be_this_user }
    access_control:
        - { path: ^/.*/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/admin, roles: [ROLE_ADMIN, ROLE_ROBOT] }
        - { path: ^/.*/admin/, roles: [ROLE_ADMIN, ROLE_ROBOT] }
        - { path: ^/.*/admin/.*, role: ROLE_ADMIN }
        - { path: ^/.*/edit-profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/settings, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/my-profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/dashboard, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/messages, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/messages/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/videostream/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/answer-call/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/photos, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/.*/.*/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }