parameters:
#    iog_admin.example.class: Iog\AdminBundle\Example

services:
#    iog_admin.example:
#        class: %iog_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    iog.extensions.admin_twig_extension:
        class: Iog\AdminBundle\Extension\TwigExtension
        arguments:    ["@service_container"]
        tags:
            - { name: twig.extension }
    iog.admin.photo_upload:
        class: Iog\AdminBundle\Service\PhotoUpload
        arguments: ['@service_container']