gallery:
    pattern:  /
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:index" }

gallery_show:
    pattern:  /{id}/show
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:show" }

gallery_new:
    pattern:  /new
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:new" }

gallery_create:
    pattern:  /create
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:create" }
    requirements: { _method: post }

gallery_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:edit" }

gallery_update:
    pattern:  /{id}/update
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:update" }
    requirements: { _method: post|put }

gallery_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:delete" }
    requirements: { _method: post|delete }
    
duedinoi_gallery_upload_photos:
    pattern: /upload-photos/{gallery_id}
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:uploadPhotos" }
    
duedinoi_gallery_image_remove:
    pattern: /remove-image
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:removeImage" }
    
duedinoi_gallery_update_image_desc:
    pattern: /update-desc/{image_id}
    defaults: { _controller: "DuedinoiAdminBundle:Gallery:updateImageDesc" }