setting:
    pattern:  /
    defaults: { _controller: "DuedinoiAdminBundle:Setting:index" }

setting_show:
    pattern:  /{id}/show
    defaults: { _controller: "DuedinoiAdminBundle:Setting:show" }

setting_new:
    pattern:  /new
    defaults: { _controller: "DuedinoiAdminBundle:Setting:new" }

setting_create:
    pattern:  /create
    defaults: { _controller: "DuedinoiAdminBundle:Setting:create" }
    requirements: { _method: post }

setting_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DuedinoiAdminBundle:Setting:edit" }

setting_update:
    pattern:  /{id}/update
    defaults: { _controller: "DuedinoiAdminBundle:Setting:update" }
    requirements: { _method: post|put }

setting_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DuedinoiAdminBundle:Setting:delete" }
    requirements: { _method: post|delete }
