<?php

namespace Duedinoi\WebBundle\Entity;

/**
 * BlockCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
