<?php

namespace Duedinoi\WebBundle\Entity;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotificationsForUser($user)
    {
        $qb = $this->createQueryBuilder('n')
                ->andWhere('n.toUser = :user_id')
                ->andWhere('n.status != :status_deleted')
                ->setParameter('user_id', $user->getId())
                ->setParameter('status_deleted', Notification::STATUS_DELETED)
                ->orderBy('n.createdAt', 'DESC');
        
        return $qb->getQuery()->execute();
    }
}
