<?php

namespace Duedinoi\WebBundle\Entity;

/**
 * ProfileReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileReportRepository extends \Doctrine\ORM\EntityRepository
{
}
