<?php

namespace Duedinoi\WebBundle\Entity;

/**
 * UserLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
