<?php

namespace Duedinoi\WebBundle\Entity;

/**
 * VideoTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoTokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIncomeCall($user)
    {
        $delay = new \DateTime('1 minute ago');
        $qb = $this->createQueryBuilder('vt')
            ->join('vt.fromUser', 'u')
            ->select('u.username, vt.token, vt.updatedAt')
            ->andWhere('vt.toUser = :user')
//            ->andWhere('vt.updatedAt > :lastMin')
            ->setParameter('user', $user->getId())
//            ->setParameter('lastMin', $delay)
            ->orderBy('vt.updatedAt' , 'desc')
            ->setMaxResults(1);

        return $qb->getQuery()->getResult();
    }
}
