Duedinoi\AdminBundle\Entity\City:
    type: entity
    table: null
    repositoryClass: Duedinoi\AdminBundle\Entity\CityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        country:
            targetEntity: Country
            inversedBy: cities
            joinColumn:
                name: country_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
