Duedinoi\AdminBundle\Entity\Country:
    type: entity
    table: duedinoi_country
    repositoryClass: Duedinoi\AdminBundle\Entity\CountryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
