duedinoi_web_homepage:
    pattern: /{_locale}
    defaults: { _controller: DuedinoiWebBundle:Default:homepage, _locale: 'it' } 
duedinoi_edit_profile:
    pattern: /{_locale}/edit-profile
    defaults: { _controller: DuedinoiWebBundle:Default:editProfile, _locale: 'it' }
duedinoi_settings:
    pattern: /{_locale}/settings
    defaults: { _controller: DuedinoiWebBundle:Default:settings, _locale: 'it' }
duedinoi_dashboard:
    pattern: /{_locale}/dashboard
    defaults: { _controller: DuedinoiWebBundle:Default:dashboard, _locale: 'it' }
duedinoi_my_profile:
    pattern: /{_locale}/my-profile
    defaults: { _controller: DuedinoiWebBundle:Default:myProfile, _locale: 'it' }
duedinoi_user_profile:
    pattern: /{_locale}/{userslug}/profile
    defaults: { _controller: DuedinoiWebBundle:Default:userProfile, _locale: 'it' }
duedinoi_user_conversation:
    pattern: /{_locale}/{userslug}/conversation
    defaults: { _controller: DuedinoiWebBundle:Default:userConversation, _locale: 'it' }
duedinoi_chat_server:
    pattern: /{_locale}/{userslug}/chat-server
    defaults: { _controller: DuedinoiWebBundle:Default:chatServer, _locale: 'it' }
