parameters:

services:
    
    duedinoi.web.page:
        class: Duedinoi\WebBundle\Service\Page
        arguments: ['@service_container']
    validator.unique.user:
        class: Duedinoi\WebBundle\Validator\Constraints\UniqueUserValidator
        tags:
            - { name: validator.constraint_validator, alias: unique_user }
        arguments: [@duedinoi.user_repository, @translator]