iog_user_process_auth:
    pattern: /process
    defaults: { _controller: DuedinoiUserBundle:Default:processAuth }
fos_user_registration_register:
    pattern: /register
    defaults: { _controller: DuedinoiUserBundle:Registration:register }