iog_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DuedinoiUserBundle:Default:index }
    
iog_user_process_auth:
    pattern: /process
    defaults: { _controller: DuedinoiUserBundle:Default:processAuth }
