parameters:
    duedinoi_user.activity_listener.class: Duedinoi\UserBundle\EventListener\ActivityListener

services:
#    iog_user.example:
#        class: %iog_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    duedinoi.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Duedinoi\UserBundle\Entity\User
            
    duedinoi_user.activity_listener:
        class: %duedinoi_user.activity_listener.class%
        arguments: [@security.context, @fos_user.user_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
