parameters:
#    iog_user.example.class: Iog\UserBundle\Example

services:
#    iog_user.example:
#        class: %iog_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    duedinoi.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Duedinoi\UserBundle\Entity\User
