<?php
namespace Cunningsoft\ChatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findBotMessage($user)
    {
        $qb = $this->createQueryBuilder('m')
                ->andWhere('m.author = :bot')
                ->setParameter('bot', $user->getId())
                ->andWhere('m.isMass = true')
                ->orderBy('m.id', 'desc');
        
        return $qb->getQuery()->execute();
    }
}
