<?php

namespace Duedinoi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Model\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getLastRegistered($limit = 12)
    {
        $qb = $this->createQueryBuilder('u')
            ->andWhere('u.roles NOT LIKE :admin')
            ->setParameter('admin', '%ROLE_ADMIN%')
            ->orderBy('u.id', 'desc')
            ->setMaxResults($limit);

        return $qb->getQuery()->execute();
    }
    
    public function findActiveExcept($user = null)
    {
        $delay = new \DateTime('2 minutes ago');
        $qb = $this
                ->createQueryBuilder('u')
                ->andWhere('u.lastActivityAt > :delay')
                ->setParameter('delay', $delay)
                ->andWhere('u.roles NOT LIKE :admin')
                ->setParameter('admin', '%ROLE_ADMIN%')
                ;
        if ($user instanceof UserInterface) {
            $qb
                ->andWhere('u.id != :user_id')
                ->setParameter('user_id', $user->getId());
        }
        
        return $qb->getQuery()->execute();
    }
}
