<?php

namespace Duedinoi\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getLastRegistered($limit = 12)
    {
        $qb = $this->createQueryBuilder('u')
            ->andWhere('u.roles NOT LIKE :admin')
            ->setParameter('admin', '%ROLE_ADMIN%')
            ->orderBy('u.id', 'desc')
            ->setMaxResults($limit);

        return $qb->getQuery()->execute();
    }
}
