<?php

namespace Duedinoi\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function findWithUser()
    {
        $qb = $this->createQueryBuilder('i')
                ->andWhere('i.user IS NOT NULL')
                ->orderBy('i.created_at', 'desc');
        
        return $qb->getQuery()->execute();
    }
}
