<?php

namespace Duedinoi\AdminBundle\Repository;

/**
 * RecruitedMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitedMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
