<?php

namespace Duedinoi\AdminBundle\Repository;

/**
 * RecruitedMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitedMemberRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBySearch($search = null)
    {
        $qb = $this->createQueryBuilder('rm');
        if ($search) {
            $qb->orWhere('rm.email LIKE :search')
                ->orWhere('rm.siteUser LIKE :search')
                ->setParameter('search', '%'.$search.'%');
        }

        return $qb->getQuery()->execute();
    }
}
