Duedinoi\WebBundle\Entity\Notification:
    type: entity
    table: duedinoi_notification
    repositoryClass: Duedinoi\WebBundle\Entity\NotificationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: integer
        type:
            type: string
            length: 255
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
            column: created_at
        updatedAt:
            type: datetime
            gedmo:
                timestampable: 
                    on: update
            column: updated_at
    manyToOne:
        fromUser:
            targetEntity: Duedinoi\UserBundle\Entity\User
            joinColumn:
                name: from_user_id
                referencedColumnName: id
        toUser:
            targetEntity: Duedinoi\UserBundle\Entity\User
            joinColumn:
                name: to_user_id
                referencedColumnName: id
        photo:
            targetEntity: Duedinoi\AdminBundle\Entity\Image
            joinColumn:
                name: photo_id
                referencerdColumnName: id
        comment:
            targetEntity: Comment
            joinColumn:
                name: comment_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
