Duedinoi\WebBundle\Entity\ProfileReport:
    type: entity
    table: null
    repositoryClass: Duedinoi\WebBundle\Entity\ProfileReportRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
            column: created_at
        updatedAt:
            type: datetime
            gedmo:
                timestampable: 
                    on: update
            column: updated_at
    manyToOne:
        fromUser:
            targetEntity: Duedinoi\UserBundle\Entity\User
            inversedBy: reportUsers
            onCascade: DELETE
            joinColumn:
                name: from_user_id
                referencedColumnName: id
        toUser:
            targetEntity: Duedinoi\UserBundle\Entity\User
            inversedBy: userReports
            onCascade: DELETE
            joinColumn:
                name: to_user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
