Duedinoi\WebBundle\Entity\UserLike:
    type: entity
    table: user_like
    repositoryClass: Duedinoi\WebBundle\Entity\UserLikeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        status:
            type: integer
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
            column: created_at
        updatedAt:
            type: datetime
            gedmo:
                timestampable: 
                    on: update
            column: updated_at
    manyToOne:
        fromUser:
            targetEntity: Duedinoi\UserBundle\Entity\User
            inversedBy: likedUsers
            onCascade: DELETE
            joinColumn:
                name: from_user_id
                referencedColumnName: id
        toUser:
            targetEntity: Duedinoi\UserBundle\Entity\User
            inversedBy: userLikes
            onCascade: DELETE
            joinColumn:
                name: to_user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
