parameters:
#    duedinoi_admin.example.class: Duedinoi\AdminBundle\Example

services:
#    duedinoi_admin.example:
#        class: %duedinoi_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    duodenoi.extensions.admin_twig_extension:
        class: Duedinoi\AdminBundle\Extension\TwigExtension
        arguments:    ["@service_container"]
        tags:
            - { name: twig.extension }
    duodenoi.admin.photo_upload:
        class: Duedinoi\AdminBundle\Service\PhotoUpload
        arguments: ['@service_container']