Duedinoi\AdminBundle\Entity\Page:
  properties:
    path:
      - NotBlank: ~
    title:
      - NotBlank: ~  
Duedinoi\UserBundle\Entity\User:
    constraints:
        - Duedinoi\WebBundle\Validator\Constraints\UniqueUser: { groups: [registration, admin] }
    properties:
        profile:
            - Valid: ~
        email:
            - NotBlank: { groups: [registration, admin] }
        plainPassword:
            - NotBlank: { groups: [registration] }
        username:
            - NotBlank: { groups: [registration, admin] }