Duedinoi\UserBundle\Entity\Profile:
    type: entity
    table: duedinoi_profile
    repositoryClass: Duedinoi\UserBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
            nullable: true
        lastName:
            type: string
            length: 255
            column: last_name
            nullable: true
        gender:
            type: integer
            nullable: true
        dateOfBirth:
            type: datetime
            nullable: true
            column: date_of_birth
        city:
            type: string
            length: 255
            nullable: true
        relationship:
            type: string
            length: 50
            nullable: true
        sign:
            type: string
            length: 50
            nullable: true
        hobby:
            type: text
            nullable: true
        studies:
            type: text
            nullable: true
        description:
            type: text
            nullable: true
        voteNotification:
            type: boolean
            nullable: true
            column: vote_notification
        commentNotification:
            type: boolean
            nullable: true
            column: comment_notification
        messageNotification:
            type: boolean
            nullable: true
            column: message_notification
    oneToOne:
        image:
            targetEntity: Duedinoi\AdminBundle\Entity\Image
            joinColumn:
                name: image_id
                referencedColumnName: id
                onDelete: 'CASCADE'
            fetch: EAGER
            cascade:
                - persist
                - remove
    lifecycleCallbacks: {  }
