Duedinoi\UserBundle\Entity\User:
    type: entity
    table: duedinoi_user
    repositoryClass: Duedinoi\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastActivityAt:
            type: datetime
            column: last_activity_at
            nullable: true
        slug:
            type: string
            length: 128
            gedmo:
              slug:
                separator: "-"
                style: default
                fields:
                  - username
        ipAddress:
            type: string
            length: 128
            nullable: true
        referral:
            type: string
            length: 255
            nullable: true
        created_at:
            type: date
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: date
            gedmo:
                timestampable: 
                    on: update
        site:
            type: string
            length: 255
            nullable: true
        confirmedAt:
            type: date
            nullable: true
    oneToOne:
        profile:
            targetEntity: Profile
            mappedBy: user
            cascade:
                - persist
                - remove
    manyToOne:
        country:
            targetEntity: Duedinoi\AdminBundle\Entity\Country
            joinColumn:
                name: country_id
                referencedColumnName: id
                onDelete: 'SET NULL'
            fetch: EAGER
            cascade:
                - persist
                - remove
        recruiter:
            targetEntity: Duedinoi\UserBundle\Entity\User
            inversedBy: recruitedUsers
            nullable: true
            joinColumn:
                name: admin_id
                referencedColumnName: id
                onDelete: 'SET NULL'
            fetch: EAGER
            cascade:
                - persist
                - remove
        converter:
            targetEntity: Duedinoi\UserBundle\Entity\User
            nullable: true
            joinColumn:
                name: converter_id
                referencedColumnName: id
                onDelete: 'SET NULL'
            fetch: EAGER
            cascade:
                - persist
                - remove
    oneToMany:
        comments:
            targetEntity: Duedinoi\WebBundle\Entity\Comment
            mappedBy: author
        receivedComments:
            targetEntity: Duedinoi\WebBundle\Entity\Comment
            mappedBy: user
        photos:
            targetEntity: Duedinoi\AdminBundle\Entity\Image
            mappedBy: user
        recruitedUsers:
            targetEntity: Duedinoi\UserBundle\Entity\User
            mappedBy: recruiter
        likedUsers:
            targetEntity: Duedinoi\WebBundle\Entity\UserLike
            mappedBy: fromUser
        userLikes:
            targetEntity: Duedinoi\WebBundle\Entity\UserLike
            mappedBy: toUser
        blockUsers:
            targetEntity: Duedinoi\WebBundle\Entity\BlockComment
            mappedBy: fromUser
        userBlocks:
            targetEntity: Duedinoi\WebBundle\Entity\BlockComment
            mappedBy: toUser
        reportUsers:
            targetEntity: Duedinoi\WebBundle\Entity\ProfileReport
            mappedBy: fromUser
        userReports:
            targetEntity: Duedinoi\WebBundle\Entity\ProfileReport
            mappedBy: toUser
    lifecycleCallbacks: {  }
