Duedinoi\UserBundle\Entity\User:
    type: entity
    table: duedinoi_user
    repositoryClass: Duedinoi\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        profile:
            targetEntity: Profile
            joinColumn:
                name: profile_id
                referencedColumnName: id
                onDelete: 'CASCADE'
            fetch: EAGER
            cascade:
                - persist
                - remove
    manyToOne:
        country:
            targetEntity: Duedinoi\AdminBundle\Entity\Country
            joinColumn:
                name: country_id
                referencedColumnName: id
                onDelete: 'SET NULL'
            fetch: EAGER
            cascade:
                - persist
                - remove
    lifecycleCallbacks: {  }
