Duedinoi\UserBundle\Entity\User:
    type: entity
    table: duedinoi_user
    repositoryClass: Duedinoi\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastActivityAt:
            type: datetime
            column: last_activity_at
            nullable: true
        slug:
            type: string
            length: 128
            gedmo:
              slug:
                separator: "-"
                style: default
                fields:
                  - username
    oneToOne:
        profile:
            targetEntity: Profile
            mappedBy: user
    manyToOne:
        country:
            targetEntity: Duedinoi\AdminBundle\Entity\Country
            joinColumn:
                name: country_id
                referencedColumnName: id
                onDelete: 'SET NULL'
            fetch: EAGER
            cascade:
                - persist
                - remove
    oneToMany:
        comments:
            targetEntity: Duedinoi\WebBundle\Entity\Comment
            mappedBy: author
        receivedComments:
            targetEntity: Duedinoi\WebBundle\Entity\Comment
            mappedBy: user
        photos:
            targetEntity: Duedinoi\AdminBundle\Entity\Image
            mappedBy: user
    lifecycleCallbacks: {  }
